name: lakehouse-local-setup
networks:
  infra_network:
    driver: bridge

services:
  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Console UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data

  aws:
    image: amazon/aws-cli
    container_name: aws-cli
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "sleep 5 &&
       aws --endpoint-url http://minio:9000 s3 mb s3://my-bucket --region eu-west-1 || true"
    environment:
      AWS_ACCESS_KEY_ID: "minioadmin"
      AWS_SECRET_ACCESS_KEY: "minioadmin"
    depends_on:
      - minio

  jupyter:
    image: jupyter/pyspark-notebook
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PYSPARK_SUBMIT_ARGS=--packages=org.apache.hadoop:hadoop-aws:3.3.4 pyspark-shell
    volumes:
      - ./notebooks:/home/jovyan/work


volumes:
  minio_data:
